apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  generateName: test-buildah-app-
spec:
  serviceAccountName: build-bot
  params:
  - name: source-repo
    value: https://github.com/TomasMachan/Test-Express-app.git
  - name: image-repo
    value: quay.io/tomasmachan/buildah
  pipelineRef:
    name: nodejs
  workspaces:
  - name: pipeline-shared-data
    volumeClaimTemplate:
      spec:
        resources:
          requests:
            storage: 1Gi
        accessModes:
        - ReadWriteOnce